# .travis.yml using container-based infrastructure

# use c as catch-all language
language: c

branches:
  only:
    - gh-pages

# use cache
cache:
  directories:
    - $HOME/Rlib

# install r-base-dev:
addons:
  apt:
    sources: r-packages-precise
    packages: r-base-dev
    
# set up R environment
install:
  - "mkdir -p ~/Rlib"
  - "echo 'R_LIBS=~/Rlib' > .Renviron"
  - "echo 'options(repos = \"http://cran.rstudio.com\")' > .Rprofile"

# install jtilly/matchingR
script:
  - Rscript -e 'options(warn = 2); source("http://jtilly.io/install_github/install_github.R"); install_github("jtilly/matchingR")'
  - Rscript -e 'options(warn = 2); source("http://jtilly.io/install_github/install_github.R"); install_github("jtilly/matchingR@master")'

# send e-mails if stuff breaks / changes
notifications:
  on_success: change
  on_failure: always
